#Anchors
x-general-blocks: &general-blocks
    networks:
        - custom-network
    env_file:
        - .env.${APP_ENV}

# Compose
name: Concord

networks:
    custom-network:
        driver: bridge

services:
    backend:
        container_name: ${APP_ENV}-concord.api
        <<: *general-blocks
        image: backend:${APP_ENV}
        build:
            context: Concord.API/
            args:
                BASE_IMAGE: shared:${APP_ENV}
        ports:
            - "${API_HTTP_PORT}:8080"
        volumes:
            - backend-uploads:/App/wwwroot/uploads
            - backend-dataprotection-keys:/App/keys
        depends_on:
            db:
                condition: service_healthy
            redis:
                condition: service_healthy
        profiles:
            - backend

    frontend:
        container_name: ${APP_ENV}-concord.frontend
        <<: *general-blocks
        image: frontend:${APP_ENV}
        build:
            context: ../../frontend/Concord
            args:
                VITE_API_URL: http://localhost:${API_HTTP_PORT}
        ports:
            - "${FRONTEND_HTTP_PORT}:80"
        profiles:
            - frontend

    db:
        container_name: ${APP_ENV}-concord.postgres
        <<: *general-blocks
        image: postgres:18
        ports:
            - "${POSTGRES_TCP_PORT}:5432"
        volumes:
            - ${POSTGRES_DIRECTORY}:/var/lib/postgresql
        healthcheck:
            # Check if Postgres is ready to accept connections
            test: ["CMD-SHELL", "pg_isready -U postgres -h localhost"]
            interval: 10s # run every 10 seconds
            timeout: 5s # fail if no response within 5 seconds
            retries: 5 # mark as unhealthy after 5 failed attempts
            start_period: 20s # wait before starting checks
        profiles:
            - db

    redis:
        container_name: ${APP_ENV}-concord.redis
        <<: *general-blocks
        image: redis:8
        ports:
            - "${REDIS_TCP_PORT}:6379"
        healthcheck:
            # Check if Redis is ready to accept connections
            test: ["CMD", "redis-cli", "ping"]
            interval: 10s # run every 10 seconds
            timeout: 5s # fail if no response within 5 seconds
            retries: 5 # mark as unhealthy after 5 failed attempts
            start_period: 10s # wait before starting checks
        profiles:
            - db

    # livekit:
    #     container_name: ${APP_ENV}-concord.livekit
    #     <<: *general-blocks
    #     image: livekit/livekit-server:latest
    #     environment:
    #         LIVEKIT_CONFIG: |
    #             port: 7880
    #             rtc:
    #                 tcp_port: 7881
    #                 port_range_start: ${LIVEKIT_RTC_PORT_START}
    #                 port_range_end: ${LIVEKIT_RTC_PORT_END}
    #                 use_external_ip: ${LIVEKIT_USE_EXTERNAL_IP}
    #             turn:
    #                 enabled: ${LIVEKIT_TURN_ENABLED}
    #                 domain: ${LIVEKIT_TURN_DOMAIN}
    #                 tls_port: 5349
    #                 udp_port: 3478
    #             keys:
    #                 ${LIVEKIT_API_KEY}: ${LIVEKIT_API_SECRET}
    #     ports:
    #         - "${LIVEKIT_HTTP_PORT}:7880"
    #         - "${LIVEKIT_TCP_PORT}:7881"
    #         - "${LIVEKIT_RTC_PORT_START}-${LIVEKIT_RTC_PORT_END}:${LIVEKIT_RTC_PORT_START}-${LIVEKIT_RTC_PORT_END}/udp"
    #         - "3478:3478/udp"
    #         - "5349:5349/tcp"
    #     healthcheck:
    #         test: ["CMD", "wget", "-qO-", "http://localhost:7880/"]
    #         interval: 10s
    #         timeout: 5s
    #         retries: 5
    #         start_period: 10s
    #     profiles:
    #         - db

    elasticsearch:
        container_name: ${APP_ENV}-concord.elasticsearch
        <<: *general-blocks
        image: docker.elastic.co/elasticsearch/elasticsearch:9.1.0
        environment:
            - discovery.type=single-node
            - xpack.security.enabled=false
            - xpack.security.http.ssl.enabled=false
        volumes:
            - ${ELASTICSEARCH_DIRECTORY}:/usr/share/elasticsearch/data
        ports:
            - "${ELASTIC_TCP_PORT}:9200"
        healthcheck:
            # Check if Elasticsearch cluster is healthy
            test:
                [
                    "CMD-SHELL",
                    "curl -s http://localhost:9200/_cluster/health || exit 1",
                ]
            interval: 20s # How often to run the check
            timeout: 10s # Time to wait for a response
            retries: 5 # Number of consecutive failures before marking as unhealthy
            start_period: 30s # Time to wait after container starts before starting healthchecks
        profiles:
            - logging

    kibana:
        container_name: ${APP_ENV}-concord.kibana
        <<: *general-blocks
        image: docker.elastic.co/kibana/kibana:9.1.0
        environment:
            - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
        ports:
            - "${KIBANA_HTTP_PORT}:5601"
        depends_on:
            - elasticsearch
        profiles:
            - logging

volumes:
    backend-uploads:
    backend-dataprotection-keys:
