FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src

COPY ./Concord.Domain/        ./Concord.Domain/
COPY ./Concord.Infrastructure ./Concord.Infrastructure/
COPY ./Concord.Application/   ./Concord.Application/